version: '3.7'

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  calendz-api-calendar:
    container_name: calendz-api-calendar
    hostname: calendz-api-calendar
    build:
      context: ../../calendz-api-calendar/
      dockerfile: Dockerfile
    image: calendz-api-calendar:1.0.0
    restart: always
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks: 
      - frontend
      - backend
    depends_on:
      - calendz-database
    command: npm run start

  calendz-api:
    container_name: calendz-api
    hostname: calendz-api
    image: calendz/api:latest
    restart: always
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    networks:
      - frontend
      - backend
    depends_on:
      - calendz-database
    command: npm run start
    env_file: ./.env

  calendz-database:
    container_name: calendz-database
    hostname: calendz-database
    image: mongo:3.6
    restart: always
    volumes:
      - ../mongodb/data:/data/db
    networks: 
      - backend
    environment:
      MONGO_INITDB_DATABASE: calendz
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password

  calendz-front:
    container_name: calendz-front
    hostname: calendz-front
    build:
      context: ../../calendz-front
      dockerfile: Dockerfile
    image: calendz-front:1.0.0
    restart: "no"
    volumes:
      - ../../calendz-front:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - calendz-api
      - calendz-api-calendar
    command: npm run build