version: '3.7'

services:
  # =============================================  
  # == CALENDZ-API-CALENDAR  
  # =============================================  
  calendz-api-calendar:
    container_name: calendz-api-calendar
    hostname: calendz-api-calendar
    image: calendz/api-calendar:current
    restart: always
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "3000:3333"
    depends_on:
      - calendz-redis
    command: npm run start
    env_file: ./.api-calendar.env

  # =============================================  
  # == CALENDZ-API  
  # =============================================  
  calendz-api:
    container_name: calendz-api
    hostname: calendz-api
    image: calendz/api:current
    restart: always
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - calendz-database
    command: npm run start
    env_file: ./.api.env

  # =============================================  
  # == CALENDZ-DATABASE  
  # =============================================      
  calendz-database:
    container_name: calendz-database
    hostname: calendz-database
    image: mongo:3.6
    restart: always
    volumes:
      - ../mongodb/data:/data/db
    env_file: ./.database.env

  # =============================================  
  # == CALENDZ-REDIS  
  # =============================================  
  calendz-redis:
    container_name: calendz-redis
    hostname: calendz-redis
    image: redis:5.0.6-alpine3.10
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}

  # =============================================
  # == CALENDZ-NGINX
  # =============================================
  calendz-nginx:
    container_name: calendz-nginx
    hostname: calendz-nginx
    build:
      context: ../nginx
      dockerfile: Dockerfile
    image: calendz/nginx:latest
    restart: always
    volumes:
      - ../nginx/conf:/etc/nginx/conf.d
      - ../nginx/data/certbot/conf:/etc/letsencrypt
      - ../nginx/data/certbot/www:/var/www/certbot
      - ../../calendz-front/dist:/var/www/calendz
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Certbot
  calendz-certbot:
    container_name: calendz-certbot
    hostname: calendz-certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ../nginx/data/certbot/conf:/etc/letsencrypt
      - ../nginx/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"