version: '3.7'

networks:
  reverse:
    driver: bridge
    internal: false
  frontend:
    internal: true
  backend-api:
    internal: true
  backend-calendar:
    internal: true
  redis:
    internal: true
  mongo:
    internal: true

services:
  # =============================================
  # == CALENDZ-NGINX
  # =============================================
  calendz-nginx:
    container_name: calendz-nginx
    hostname: calendz-nginx
    build:
      context: ../nginx
      dockerfile: Dockerfile
    image: calendz/nginx:latest
    restart: always
    volumes:
      - ../nginx/conf:/etc/nginx/conf.d
      - ../../calendz-front/dist:/var/www/calendz
    networks:
      - reverse
      - frontend
      - backend-api
      - backend-calendar
    ports:
      - "8800:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  calendz-api-calendar:
    container_name: calendz-api-calendar
    hostname: calendz-api-calendar
    build:
      context: ../../calendz-api-calendar/
      dockerfile: Dockerfile
    image: calendz-api-calendar:latest
    restart: on-failure
    volumes:
      - ../../calendz-api-calendar:/usr/src/app
      - /usr/src/app/node_modules
    networks: 
      - backend-calendar
      - redis
    depends_on:
      - calendz-redis
    command: npm run dev

  calendz-api:
    container_name: calendz-api
    hostname: calendz-api
    build:
      context: ../../calendz-api/
      dockerfile: Dockerfile
    image: calendz-api:latest
    restart: on-failure
    volumes:
      - ../../calendz-api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend-api
      - mongo
    depends_on:
      - calendz-database
    command: npm run dev

  calendz-database:
    container_name: calendz-database
    hostname: calendz-database
    image: mongo:latest
    restart: on-failure
    networks: 
      - mongo
    environment:
      MONGO_INITDB_DATABASE: calendz
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password

  calendz-front:
    container_name: calendz-front
    hostname: calendz-front
    build:
      context: ../../calendz-front
      dockerfile: Dockerfile
    image: calendz-front:latest
#    restart: on-failure
    volumes:
      - ../../calendz-front:/usr/src/app
      - ../../calendz-front-npm-log:/root/.npm/_logs
      - /usr/src/app/node_modules
    networks: 
      - frontend
    depends_on:
      - calendz-api
      - calendz-api-calendar
    command: npm run dev

  calendz-redis:
    container_name: calendz-redis
    hostname: calendz-redis
    image: redis:5.0.6-alpine3.10
    restart: unless-stopped
    networks: 
      - redis
    command: redis-server
